In [1]:
import numpy as np

# create a numpy array
a = np.array([1, 2, 3, 4])
print("a=", a)

a= [1 2 3 4]


In [2]:
#matrix
b = np.array([[1, 2], [3, 4]])
print("b=", b)


b= [[1 2]
 [3 4]]


In [3]:
#shape
print(a.shape)
print(b.shape)

(4,)
(2, 2)


In [4]:
#reshape
c = a.reshape((4, 1))
print("c=", c)
print(c.shape)

d = a.reshape((2,-1,1))
print(d.shape)

c= [[1]
 [2]
 [3]
 [4]]
(4, 1)
(2, 2, 1)


In [21]:
# concatenate
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = np.concatenate((a, b))
print("c=",c)
print(c.shape)

c= [1 2 3 4 5 6]
(6,)


In [6]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = a * b
print("c", c)

c [ 4 10 18]


In [7]:
#broadcasting
c = np.array([10])

d = a + c
print("d=", d)


e = a + 10
print ("e", e)

d= [11 12 13]
e [11 12 13]


In [8]:
#slicing
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(a.shape)

b = a[2:7:2]
print("b=", b)

(8,)
b= [3 5 7]


In [9]:
c = a[a>3]
print("c=", c)

c= [4 5 6 7 8]


In [ ]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])

sum_a = np.sum(a)
print("sum=", sum_a)

max_a = np.max(a)
print("max", max_a)

min_a = np.min(a)
print("min", min_a)

sum= 36
max 8
min 1


In [ ]:
#sort
a = np.array([4, 2, 9, 6, 7, 3, 5])
b = np.sort(a)
b

array([2, 3, 4, 5, 6, 7, 9])

In [ ]:
#random
a = np.random.randint(-100, 100, (3,4))
a

array([[ 43,  67,  74,  12],
       [ 18,  40, -99, -10],
       [ 72,  72,  82, -94]], dtype=int32)

In [30]:
#stacking
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = np.vstack((a, b))
print(c.shape)
print("c=", c)


(2, 3)
c= [[1 2 3]
 [4 5 6]]


In [31]:
d = np.hstack((a, b))
print(d.shape)
print("d=", d)


(6,)
d= [1 2 3 4 5 6]


In [34]:
#normalize

a = np.array([1, 2, 3])
mean_a = np.mean(a)
mean_a

np.float64(2.0)

In [36]:
std_a = np.std(a)
std_a

np.float64(0.816496580927726)

In [37]:
norm_a = (a - mean_a) / std_a
norm_a

array([-1.22474487,  0.        ,  1.22474487])

In [38]:
np.mean(norm_a)

np.float64(0.0)

In [39]:
np.std(norm_a)

np.float64(0.9999999999999999)